# Generated by Django 6.0.1 on 2026-01-29 12:45

import django.db.models.deletion
from django.db import migrations, models

import lists.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GiftList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "slug",
                    models.CharField(
                        db_index=True,
                        default=lists.models.generate_unique_slug,
                        max_length=8,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=500)),
                ("title", models.CharField(blank=True, max_length=500)),
                ("price", models.CharField(blank=True, max_length=50, null=True)),
                ("image_url", models.URLField(blank=True, max_length=500, null=True)),
                ("is_reserved", models.BooleanField(default=False)),
                (
                    "reserved_by_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "gift_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="lists.giftlist",
                    ),
                ),
            ],
        ),
    ]
